void patch();
void draw3D();
void reshape(GLsizei width, GLsizei height);
void KeyboardManagement(unsigned char key, int x, int y);
void MouseManagement(int button, int state, int x, int y);
void ArrowkeysManagement(int key, int x, int y);
void delete_World();
void init_World();
void init_stats();
void init_menu();
void affich_message(unsigned char test);
void affich_credits();
void radius_min_max();
void draw_snowman();